pipeline {
    agent any
    
    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/balasagar0/hospital-management-system.git'
            }
        }
        
        stage('Build') {
            steps {
                dir('hospital-backend-jenkins') {
                    sh 'mvn clean package'
                }
            }
        }
        
        stage('Deploy') {
            steps {
                dir('hospital-backend-jenkins') {
                    sh '''
                        pkill -f "hospital-1.0.0.war" || true
                        nohup java -jar target/hospital-1.0.0.war --server.port=8080 > app.log 2>&1 &
                        sleep 30
                    '''
                }
            }
        }
    }
}
